bitbot.driveMilliseconds(200, 400)
basic.forever(function () {
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Blue))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Green))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Red))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Purple))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.White))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Violet))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Orange))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Yellow))
    basic.pause(500)
    bitbot.neoSetColor(bitbot.BBColours(BBColors.Indigo))
})
